services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'

  admin:
    build:
      context: .
    ports:
      - "1234:1234"
    environment:
      - PORT=8080
      - DATABASE_URL={REPLACE_ME}
      - ADMIN_USERNAME=adminTax
      - ADMIN_PASSWORD=admin!
